#!/bin/sh
# homebrew-formula.sh — emit the Homebrew formula for one released version,
# reading the archive checksums from dist/SHA256SUMS (run scripts/dist.sh
# first). Upstream-binary formula: installs the exact attested release
# artifacts instead of rebuilding, so `brew install` is fast and what you
# run is what the release workflow attested.
#
# Usage: scripts/homebrew-formula.sh <version>   (e.g. v0.1.0)
set -eu

cd "$(dirname "$0")/.."
version=${1:?usage: homebrew-formula.sh <version>}
plain=${version#v}
sums=dist/SHA256SUMS
[ -f "$sums" ] || { echo "missing $sums — run scripts/dist.sh $version first" >&2; exit 1; }

sha() {
  grep "loopy_${version}_$1.tar.gz" "$sums" | cut -d' ' -f1
}

cat <<EOF
# typed: false
# frozen_string_literal: true

# loopy.rb — generated by scripts/homebrew-formula.sh $version
# Stable releases only; RCs never land in the tap.
class Loopy < Formula
  desc "Engineer coding-agent loops: goal + verifier + budget, reviewed diffs out"
  homepage "https://github.com/mjbarefo/loopy"
  version "$plain"
  license "MIT"

  livecheck do
    url :homepage
    strategy :github_latest
  end

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/mjbarefo/loopy/releases/download/$version/loopy_${version}_darwin_arm64.tar.gz"
      sha256 "$(sha darwin_arm64)"
    else
      url "https://github.com/mjbarefo/loopy/releases/download/$version/loopy_${version}_darwin_amd64.tar.gz"
      sha256 "$(sha darwin_amd64)"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/mjbarefo/loopy/releases/download/$version/loopy_${version}_linux_arm64.tar.gz"
      sha256 "$(sha linux_arm64)"
    else
      url "https://github.com/mjbarefo/loopy/releases/download/$version/loopy_${version}_linux_amd64.tar.gz"
      sha256 "$(sha linux_amd64)"
    end
  end

  def install
    bin.install "loopy"
  end

  test do
    assert_match "loopy $version", shell_output("#{bin}/loopy version")
  end
end
EOF
